### ISSUE TITLE
Support api 1.1?

### ISSUE THREAD

**Issue by karlicoss** [rsgalloway/instapaper#11]
Currently I'm just hacking it via setting `_API_VERSION_ = "api/1.1"` in my script.

It might require some extra effort, e.g. bookmarks API method is now returning [dictionary instead of list](https://www.instapaper.com/api), so `bookmarks` method will need fixing.

I was using `bookmarks_raw` method that I added in https://github.com/rsgalloway/instapaper/pull/10 , so that's not a problem for me, but leaving it here in case other people are wondering. I'll keep updated if I discover which other methods need to be fixed too.

**Comment by johntomczak** [comment]
I have been working on some personal fixes / additions to Instapaper for a while now, too. I am now trying to clear out my starred folder, just because, but think that the problem you highlighted with the new API features is causing me trouble. Do you think you can help me?
--
Calling: 

for bm in i.bookmarks( limit=5000,folder="starred" ):
    # bm.move( new_fid )
    print( bm.title )

Results in:

Traceback (most recent call last):
  File "mega_archive.py", line 35, in <module>
    for bm in i.bookmarks( limit=5000,folder="starred" ):
  File "/Library/Python/2.7/site-packages/instapaper.py", line 345, in bookmarks
    response, data = self.http.request(
AttributeError: 'NoneType' object has no attribute 'request'
